### PR TITLE
Add Test 24: Multimachine system with Dynamic Branches

### PR DESCRIPTION
**Pull request by rodrigomha**
The following PR adds test 24:

_This case study a three-bus system, with two Marconato generators (in buses 1 and 2), and a constant impedance load in bus 3. The perturbation increase the reference of mechanical power of generator-2 from 0.8 to 0.9 at t=1.0s._

All buses and lines are now differential equations, while using fluxes in generator models.

Nevertheless, the stiffness of the system is so large, that I'm not sure IDA is able to properly integrate without considering internally such dynamics as algebraic.

For example, with the current parameters, eigenvalues of buses and lines are in the order of 1000 to 10000 for the real part, while most of the other dynamics are in the order of 1 to 100. 

@m-bossart and @jd-lara This is the example that we are interested in comparing to PSCAD, so we will be (probably) debugging for a while.

### CODE REVIEW

**Review by jd-lara — CHANGES_REQUESTED** [review]
We need to add the mass matrix version of this test before merging

**Comment by jd-lara** [comment]
@rodrigomha can we update this PR to merge for 0.6?

**Comment by jd-lara** [comment]
@rodrigomha I am going to merge this to master since it has a lot of commits and refine the tests in a subsequent PR.

**Comment by m-bossart** [comment]
For the PSCAD test, can we check the voltage magnitudes? The Power/Frequencies are hard to match up exactly. Same issue as before with the AVRs, if we don't have a governor on one of the generators, there will be some (small) discrepancy in P or frequency.

**Comment by jd-lara** [comment]
I think that is fine but it will good to figure out where the differences are coming from at least so we can explain it.

**Comment by m-bossart** [comment]
There is an Iron Loss Resistance parameter for the machine in PSCAD which is modeled as a shunt resistance at the terminal. If there is some additional loss, then the references won't match exactly. I think it is reasonable to as a rule always include gov+avr when testing SGs vs PSCAD. Because we want to focus on the transient results, not the minutia of reaching exact same steady state solution.

**Comment by m-bossart** [comment]
I will add the voltage comparison for test25 for now.

**Comment by jd-lara** [comment]
> There is an Iron Loss Resistance parameter for the machine in PSCAD which is modeled as a shunt resistance at the terminal. If there is some additional loss, then the references won't match exactly. I think it is reasonable to as a rule always include gov+avr when testing SGs vs PSCAD. Because we want to focus on the transient results, not the minutia of reaching exact same steady state solution.

Can you add as a note as a comment in the test file please?

**Pull request merged**
